name: Deploy Vite Dashboard to Lightsail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build Vite project
      run: npm run build

    - name: Upload to temp folder
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.FRONTEND_SSH_KEY }}
        source: "dist/**"
        target: "/home/ubuntu/dashboard-temp"
        strip_components: 1

    - name: Replace production build on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.FRONTEND_SSH_KEY }}
        script: |
          sudo rm -rf /home/ubuntu/dashboard-frontend/*
          sudo mv /home/ubuntu/dashboard-temp/* /home/ubuntu/dashboard-frontend/
          sudo rm -rf /home/ubuntu/dashboard-temp
          sudo chown -R www-data:www-data /home/ubuntu/dashboard-frontend
          sudo chmod -R 755 /home/ubuntu/dashboard-frontend
