name: Deploy Vite Dashboard to Lightsail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build Vite project
      run: npm run build

    - name: Upload build to Lightsail
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.FRONTEND_SSH_KEY }}
        source: "dist/**"
        target: "/home/ubuntu/dashboard-frontend"
        strip_components: 1
        overwrite: true
